name: Automate - Changeset Feedback

on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write
  contents: none

jobs:
  feedback:
    # Prevent running on forks and on PRs from the bot
    if: |
      (github.repository == 'wasmCloud/typescript') &&
      (github.event.pull_request.user.login != 'wasmcloud-automation-app[bot]')
    runs-on: ubuntu-latest
    steps:
      # Comparing target commit ref to base ref means minimal history is needed for comparison
      - name: Checkout PR
        # Fetch the PR commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: 'refs/pull/${{ github.event.pull_request.number }}/merge'

      - name: Fetch Base ref
        # Fetch the base ref
        run: git fetch --depth 1 origin ${{ github.base_ref }}

      # Feedback is applied only to PR's that actually change code that would be part of a release
      - name: Generate feedback
        uses: backstage/actions/changeset-feedback@d98113056c83b1b0a1293c8310d77d99db4ea22e # v0.7.3
        with:
          diff-ref: origin/main
          issue-number: ${{ github.event.pull_request.number }}
          bot-username: wasmcloud-automation-app[bot]
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          installation-id: ${{ secrets.BOT_APP_INSTALLATION_ID }}
